### ISSUE TITLE
Periodic TODO list

### ISSUE THREAD

**Issue by goirijo** [goirijo/casm-utilities#17]
This will serve as a running todo list for prioritized features. Only check boxes if the routine running c++ code with tests AND running python code with tests.
- [x] `make_niggli` overload for `Lattice`
- [x] `make_superstructure`
- [x] `make_point_group`
- [x] `make_factor_group`
- [x] `CartOp`

**Comment by goirijo** [comment]
Yay we did it
