### ISSUE TITLE
Periodic TODO list

### ISSUE THREAD

**Issue by goirijo** [goirijo/casm-utilities#22]
- [ ] Documentation for each structure mapping parameter
- [ ] Rename `MappingInput` to something better
- [ ] Allow constructing `Site` with raw vector
- [ ] Clarify what `options` are in the in the mapping options
- [ ] Add factor group tolerance as a parameter for structure mapping
- [ ] Switch to binary comparators
- [ ] Rename `Structure::within`
